sudo: required
services:
    - docker

before_install:
    - docker build -t shakilabdin/docker-react -f Dockerfile.dev .

script: 
    - docker run -e CI=true shakilabdin/docker-react npm run test

deploy:
    provider: elasticbeanstalk
    region: "us-east-1"
    app: "docker-react"
    env: "DockerReact-env-1"
    bucket_name: "elasticbeanstalk-us-east-1-853395256906"
    bucket_path: "docker-react"
    on:
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY



